version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=123123123123
      - ALLOWED_HOSTS=127.0.0.1,localhost
  
  proxy:
    build:
      context: ./proxy
    ports:
      - '8080:8080'
    depends_on: 
      - app