# Generated by Django 3.1.2 on 2020-10-27 18:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_ID', models.IntegerField()),
                ('Model_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make_ID', models.IntegerField()),
                ('Make_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_car', to='cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='Maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_maker', to='cars.maker'),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('Model_ID', 'Model_Name')},
        ),
    ]
